# N001 – LendingClub Dataset Discovery Summary

## Discovery Objective

The purpose of this notebook is to understand the LendingClub dataset before building:

* Clean Layer
* Core Warehouse
* Data Marts
* Feature Store
* Modeling Dataset
* Credit Risk Models

The objective is to eliminate assumptions and design the platform using evidence from the data.

---

# Dataset Overview

| Metric                   | Value                       |
| ------------------------ | --------------------------- |
| Dataset                  | LendingClub Accepted Loans  |
| Source File              | accepted_2007_to_2018Q4.csv |
| Raw Rows Loaded          | 2,260,701                   |
| Columns                  | 151                         |
| Valid Loan Records       | 2,260,668                   |
| Footer / Summary Records | 33                          |
| Primary Key              | id                          |
| member_id Population     | 0                           |
| Earliest Issue Date      | Apr-2008                    |
| Latest Issue Date        | Sep-2018                    |
| Application Types        | Individual, Joint App       |

---

# Dataset Grain

## Grain Definition

```text
1 Row = 1 Loan
```

Evidence:

| Metric            |     Value |
| ----------------- | --------: |
| Valid Loans       | 2,260,668 |
| Distinct Loan IDs | 2,260,668 |

Result:

```text
Loan ID is unique.
```

---

# Primary Key Assessment

## Candidate Key Analysis

| Column    | Distinct Values | Conclusion    |
| --------- | --------------: | ------------- |
| id        |       2,260,668 | Primary Key   |
| member_id |               0 | Invalid       |
| url       |       2,260,668 | Nearly Unique |
| loan_amnt |           1,572 | Not Unique    |

## Selected Primary Key

```text
id
```

---

# Deprecated Fields

## member_id

Findings:

| Metric            |     Value |
| ----------------- | --------: |
| Total Records     | 2,260,701 |
| Populated Records |         0 |

Decision:

```text
member_id is deprecated.
```

This field will not be used in:

* Cleaning
* Warehouse
* Marts
* Features
* Modeling

---

# Footer Records Discovery

The raw file contains 33 non-loan records.

Examples:

```text
Total amount funded in policy code 1: ...
Total amount funded in policy code 2: ...
Loans that do not meet the credit policy
```

These records are dataset summaries and not actual loans.

## Cleaning Rule #1

```sql
try_cast(id as bigint) is not null
```

Valid loan records satisfy this condition.

---

# Time Coverage

## Issue Date Coverage

| Metric             | Value    |
| ------------------ | -------- |
| Minimum Issue Date | Apr-2008 |
| Maximum Issue Date | Sep-2018 |

Observation:

Although the file name references 2007–2018Q4, valid loan records begin in Apr-2008.

---

# Application Types

| Application Type |     Loans |
| ---------------- | --------: |
| Individual       | 2,139,958 |
| Joint App        |   120,710 |

## Distribution

| Application Type | Percentage |
| ---------------- | ---------: |
| Individual       |     94.66% |
| Joint App        |      5.34% |

Decision:

```text
Joint application fields will be retained.
```

The population is sufficiently large to justify dedicated analysis.

---

# Business Entities and Attributes

## Entity 1 — Loan

Primary business entity.

### Attributes

```text
id
loan_amnt
funded_amnt
funded_amnt_inv
term
int_rate
installment
grade
sub_grade
issue_d
loan_status
purpose
title
policy_code
application_type
disbursement_method
initial_list_status
pymnt_plan
url
```

---

## Entity 2 — Borrower

Borrower demographic and financial profile.

### Attributes

```text
annual_inc
home_ownership
emp_title
emp_length
verification_status
dti
zip_code
addr_state
```

---

## Entity 3 — Credit Profile

Borrower credit bureau profile at origination.

### Attributes

```text
fico_range_low
fico_range_high
earliest_cr_line

delinq_2yrs
inq_last_6mths
open_acc
pub_rec
revol_bal
revol_util
total_acc

collections_12_mths_ex_med
mths_since_last_major_derog
acc_now_delinq
tot_coll_amt
tot_cur_bal

acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc_util

chargeoff_within_12_mths
delinq_amnt

mo_sin_old_il_acct
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl

mort_acc

mths_since_recent_bc
mths_since_recent_bc_dlq
mths_since_recent_inq
mths_since_recent_revol_delinq

num_accts_ever_120_pd
num_actv_bc_tl
num_actv_rev_tl
num_bc_sats
num_bc_tl
num_il_tl
num_op_rev_tl
num_rev_accts
num_rev_tl_bal_gt_0
num_sats

num_tl_120dpd_2m
num_tl_30dpd
num_tl_90g_dpd_24m
num_tl_op_past_12m

pct_tl_nvr_dlq
percent_bc_gt_75

pub_rec_bankruptcies
tax_liens

tot_hi_cred_lim
total_bal_ex_mort
total_bc_limit
total_il_high_credit_limit
total_rev_hi_lim
```

---

## Entity 4 — Payment Performance

Loan repayment and collections performance.

### Attributes

```text
out_prncp
out_prncp_inv

total_pymnt
total_pymnt_inv

total_rec_prncp
total_rec_int
total_rec_late_fee

recoveries
collection_recovery_fee

last_pymnt_d
last_pymnt_amnt

next_pymnt_d

last_credit_pull_d

last_fico_range_low
last_fico_range_high
```

---

## Entity 5 — Joint Applicant

Joint borrower information.

### Attributes

```text
annual_inc_joint
dti_joint
verification_status_joint

revol_bal_joint

sec_app_fico_range_low
sec_app_fico_range_high

sec_app_earliest_cr_line

sec_app_inq_last_6mths

sec_app_mort_acc
sec_app_open_acc
sec_app_revol_util
sec_app_open_act_il

sec_app_num_rev_accts

sec_app_chargeoff_within_12_mths
sec_app_collections_12_mths_ex_med

sec_app_mths_since_last_major_derog
```

---

## Entity 6 — Hardship Program

Borrowers enrolled in hardship assistance programs.

### Attributes

```text
hardship_flag
hardship_type
hardship_reason
hardship_status

hardship_amount
hardship_length
hardship_dpd

hardship_start_date
hardship_end_date

payment_plan_start_date

hardship_loan_status

deferral_term

orig_projected_additional_accrued_interest

hardship_payoff_balance_amount

hardship_last_payment_amount
```


## Entity 7 — Debt Settlement Program

Loans entering settlement.

### Attributes

```text
debt_settlement_flag
debt_settlement_flag_date

settlement_status
settlement_date

settlement_amount
settlement_percentage
settlement_term
```

---

## Entity 8 — Revolving / Installment Utilization

Advanced utilization and exposure metrics.

### Attributes

```text
open_acc_6m
open_act_il

open_il_12m
open_il_24m

mths_since_rcnt_il

total_bal_il
il_util

open_rv_12m
open_rv_24m

max_bal_bc

all_util

inq_fi
total_cu_tl
inq_last_12m
```

---

# Preliminary Entity Relationship Model

```text
Borrower
    |
    | 1:N
    |
Loan (Primary Entity)
    |
    +---- Credit Profile
    |
    +---- Payment Performance
    |
    +---- Joint Applicant
    |
    +---- Hardship Program
    |
    +---- Debt Settlement Program
    |
    +---- Utilization Metrics
```

---

# Major Data Quality Findings

## Finding 1

```text
member_id = 100% null
```

Impact:

Borrower-level identity cannot be constructed from source data.

---

## Finding 2

Joint applicant fields are sparse but important.

Approximately 5% of loans are joint applications.

---

## Finding 3

Hardship fields are highly sparse.

Only hardship participants populate these attributes.

---

## Finding 4

Settlement fields are highly sparse.

Only settlement cases populate these attributes.

---

## Finding 5

Footer records are embedded in the source file.

These must be removed during cleaning.

---

# Architectural Implications

## Important Discovery

The dataset does not contain a reliable borrower identifier.

Because:

```text
member_id = NULL for all records
```

the platform should initially be designed as:

```text
Loan-Centric
```

rather than:

```text
Borrower-Centric
```

until a stable borrower key can be derived.

---

# Discovery Decisions

| Decision          | Outcome            |
| ----------------- | ------------------ |
| Grain             | 1 Row = 1 Loan     |
| Primary Key       | id                 |
| member_id         | Deprecated         |
| Footer Records    | Remove             |
| Joint App Fields  | Retain             |
| Hardship Fields   | Retain             |
| Settlement Fields | Retain             |
| Warehouse Design  | Loan-Centric       |
| Next Phase        | Clean Layer Design |

---



```
```

In [2]:
from pathlib import Path

import duckdb
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)

In [3]:
ROOT = Path(
    r"D:\Project_Lighthouse"
)

DB_PATH = (
    ROOT
    / "projects"
    / "P0_Data_Platform"
    / "datasets"
    / "lendingclub"
    / "data"
    / "warehouse"
    / "duckdb"
    / "lendingclub.duckdb"
)

conn = duckdb.connect(str(DB_PATH))

print(DB_PATH)

D:\Project_Lighthouse\projects\P0_Data_Platform\datasets\lendingclub\data\warehouse\duckdb\lendingclub.duckdb

In [3]:
snapshot = conn.execute(
    """
    select
        count(*) as row_count
    from raw.lendingclub_raw
    """
).fetchdf()

snapshot

   row_count
0    2260701

In [4]:
columns_df = conn.execute(
    """
    select
        column_name,
        data_type
    from information_schema.columns
    where table_schema='raw'
      and table_name='lendingclub_raw'
    order by ordinal_position
    """
).fetchdf()

columns_df

                                    column_name data_type
0                                            id   VARCHAR
1                                     member_id   VARCHAR
2                                     loan_amnt    DOUBLE
3                                   funded_amnt    DOUBLE
4                               funded_amnt_inv    DOUBLE
5                                          term   VARCHAR
6                                      int_rate    DOUBLE
7                                   installment    DOUBLE
8                                         grade   VARCHAR
9                                     sub_grade   VARCHAR
10                                    emp_title   VARCHAR
11                                   emp_length   VARCHAR
12                               home_ownership   VARCHAR
13                                   annual_inc    DOUBLE
14                          verification_status   VARCHAR
15                                      issue_d   VARCHAR
16                                  loan_status   VARCHAR
17                                   pymnt_plan   VARCHAR
18                                          url   VARCHAR
19                                         desc   VARCHAR
20                                      purpose   VARCHAR
21                                        title   VARCHAR
22                                     zip_code   VARCHAR
23                                   addr_state   VARCHAR
24                                          dti    DOUBLE
25                                  delinq_2yrs    DOUBLE
26                             earliest_cr_line   VARCHAR
27                               fico_range_low    DOUBLE
28                              fico_range_high    DOUBLE
29                               inq_last_6mths    DOUBLE
30                       mths_since_last_delinq    DOUBLE
31                       mths_since_last_record    DOUBLE
32                                     open_acc    DOUBLE
33                                      pub_rec    DOUBLE
34                                    revol_bal    DOUBLE
35                                   revol_util    DOUBLE
36                                    total_acc    DOUBLE
37                          initial_list_status   VARCHAR
38                                    out_prncp    DOUBLE
39                                out_prncp_inv    DOUBLE
40                                  total_pymnt    DOUBLE
41                              total_pymnt_inv    DOUBLE
42                              total_rec_prncp    DOUBLE
43                                total_rec_int    DOUBLE
44                           total_rec_late_fee    DOUBLE
45                                   recoveries    DOUBLE
46                      collection_recovery_fee    DOUBLE
47                                 last_pymnt_d   VARCHAR
48                              last_pymnt_amnt    DOUBLE
49                                 next_pymnt_d   VARCHAR
50                           last_credit_pull_d   VARCHAR
51                         last_fico_range_high    DOUBLE
52                          last_fico_range_low    DOUBLE
53                   collections_12_mths_ex_med    DOUBLE
54                  mths_since_last_major_derog    DOUBLE
55                                  policy_code    DOUBLE
56                             application_type   VARCHAR
57                             annual_inc_joint    DOUBLE
58                                    dti_joint    DOUBLE
59                    verification_status_joint   VARCHAR
60                               acc_now_delinq    DOUBLE
61                                 tot_coll_amt    DOUBLE
62                                  tot_cur_bal    DOUBLE
63                                  open_acc_6m    DOUBLE
64                                  open_act_il    DOUBLE
65                                  open_il_12m    DOUBLE
66                                  open_il_24m    DOUBLE
67                           mths_since_rcnt_il    DOUBLE
68                                 total_bal_il    DOUBLE
69                                      il_util    DOUBLE
70                                  open_rv_12m    DOUBLE
71                                  open_rv_24m    DOUBLE
72                                   max_bal_bc    DOUBLE
73                                     all_util    DOUBLE
74                             total_rev_hi_lim    DOUBLE
75                                       inq_fi    DOUBLE
76                                  total_cu_tl    DOUBLE
77                                 inq_last_12m    DOUBLE
78                         acc_open_past_24mths    DOUBLE
79                                  avg_cur_bal    DOUBLE
80                               bc_open_to_buy    DOUBLE
81                                      bc_util    DOUBLE
82                     chargeoff_within_12_mths    DOUBLE
83                                  delinq_amnt    DOUBLE
84                           mo_sin_old_il_acct    DOUBLE
85                         mo_sin_old_rev_tl_op    DOUBLE
86                        mo_sin_rcnt_rev_tl_op    DOUBLE
87                               mo_sin_rcnt_tl    DOUBLE
88                                     mort_acc    DOUBLE
89                         mths_since_recent_bc    DOUBLE
90                     mths_since_recent_bc_dlq    DOUBLE
91                        mths_since_recent_inq    DOUBLE
92               mths_since_recent_revol_delinq    DOUBLE
93                        num_accts_ever_120_pd    DOUBLE
94                               num_actv_bc_tl    DOUBLE
95                              num_actv_rev_tl    DOUBLE
96                                  num_bc_sats    DOUBLE
97                                    num_bc_tl    DOUBLE
98                                    num_il_tl    DOUBLE
99                                num_op_rev_tl    DOUBLE
100                               num_rev_accts    DOUBLE
101                         num_rev_tl_bal_gt_0    DOUBLE
102                                    num_sats    DOUBLE
103                            num_tl_120dpd_2m    DOUBLE
104                                num_tl_30dpd    DOUBLE
105                          num_tl_90g_dpd_24m    DOUBLE
106                          num_tl_op_past_12m    DOUBLE
107                              pct_tl_nvr_dlq    DOUBLE
108                            percent_bc_gt_75    DOUBLE
109                        pub_rec_bankruptcies    DOUBLE
110                                   tax_liens    DOUBLE
111                             tot_hi_cred_lim    DOUBLE
112                           total_bal_ex_mort    DOUBLE
113                              total_bc_limit    DOUBLE
114                  total_il_high_credit_limit    DOUBLE
115                             revol_bal_joint    DOUBLE
116                      sec_app_fico_range_low    DOUBLE
117                     sec_app_fico_range_high    DOUBLE
118                    sec_app_earliest_cr_line   VARCHAR
119                      sec_app_inq_last_6mths    DOUBLE
120                            sec_app_mort_acc    DOUBLE
121                            sec_app_open_acc    DOUBLE
122                          sec_app_revol_util    DOUBLE
123                         sec_app_open_act_il    DOUBLE
124                       sec_app_num_rev_accts    DOUBLE
125            sec_app_chargeoff_within_12_mths    DOUBLE
126          sec_app_collections_12_mths_ex_med    DOUBLE
127         sec_app_mths_since_last_major_derog    DOUBLE
128                               hardship_flag   VARCHAR
129                               hardship_type   VARCHAR
130                             hardship_reason   VARCHAR
131                             hardship_status   VARCHAR
132                               deferral_term    DOUBLE
133                             hardship_amount    DOUBLE
134                         hardship_start_date   VARCHAR
135                           hardship_end_date   VARCHAR
136                     payment_plan_start_date   VARCHAR
137                             hardship_length    DOUBLE
138                                hardship_dpd    DOUBLE
139                        hardship_loan_status   VARCHAR
140  orig_projected_additional_accrued_interest    DOUBLE
141              hardship_payoff_balance_amount    DOUBLE
142                hardship_last_payment_amount    DOUBLE
143                         disbursement_method   VARCHAR
144                        debt_settlement_flag   VARCHAR
145                   debt_settlement_flag_date   VARCHAR
146                           settlement_status   VARCHAR
147                             settlement_date   VARCHAR
148                           settlement_amount    DOUBLE
149                       settlement_percentage    DOUBLE
150                             settlement_term    DOUBLE

In [5]:
len(columns_df)

151

In [6]:
conn.execute(
    """
    select *
    from raw.lendingclub_raw
    limit 5
    """
).fetchdf()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_act_il,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,acc_open_past_24mths,avg_cur_bal,bc_open_to_buy,bc_util,chargeoff_within_12_mths,delinq_amnt,mo_sin_old_il_acct,mo_sin_old_rev_tl_op,mo_sin_rcnt_rev_tl_op,mo_sin_rcnt_tl,mort_acc,mths_since_recent_bc,mths_since_recent_bc_dlq,mths_since_recent_inq,mths_since_recent_revol_delinq,num_accts_ever_120_pd,num_actv_bc_tl,num_actv_rev_tl,num_bc_sats,num_bc_tl,num_il_tl,num_op_rev_tl,num_rev_accts,num_rev_tl_bal_gt_0,num_sats,num_tl_120dpd_2m,num_tl_30dpd,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,revol_bal_joint,sec_app_fico_range_low,sec_app_fico_range_high,sec_app_earliest_cr_line,sec_app_inq_last_6mths,sec_app_mort_acc,sec_app_open_acc,sec_app_revol_util,sec_app_open_act_il,sec_app_num_rev_accts,sec_app_chargeoff_within_12_mths,sec_app_collections_12_mths_ex_med,sec_app_mths_since_last_major_derog,hardship_flag,hardship_type,hardship_reason,hardship_status,deferral_term,hardship_amount,hardship_start_date,hardship_end_date,payment_plan_start_date,hardship_length,hardship_dpd,hardship_loan_status,orig_projected_additional_accrued_interest,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,None,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,leadman,10+ years,MORTGAGE,55000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,None,debt_consolidation,Debt consolidation,190xx,PA,5.91,0.0,Aug-2003,675.0,679.0,1.0,30.0,NaN,7.0,0.0,2765.0,29.7,13.0,w,0.00,0.00,4421.723917,4421.72,3600.00,821.72,0.0,0.0,0.0,Jan-2019,122.67,None,Mar-2019,564.0,560.0,0.0,30.0,1.0,Individual,NaN,NaN,None,0.0,722.0,144904.0,2.0,2.0,0.0,1.0,21.0,4981.0,36.0,3.0,3.0,722.0,34.0,9300.0,3.0,1.0,4.0,4.0,20701.0,1506.0,37.2,0.0,0.0,148.0,128.0,3.0,3.0,1.0,4.0,69.0,4.0,69.0,2.0,2.0,4.0,2.0,5.0,3.0,4.0,9.0,4.0,7.0,0.0,0.0,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,None,None,None,NaN,NaN,None,None,None,NaN,NaN,None,NaN,NaN,NaN,Cash,N,None,None,None,NaN,NaN,NaN
1,68355089,None,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,Engineer,10+ years,MORTGAGE,65000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,None,small_business,Business,577xx,SD,16.06,1.0,Dec-1999,715.0,719.0,4.0,6.0,NaN,22.0,0.0,21470.0,19.2,38.0,w,0.00,0.00,25679.660000,25679.66,24700.00,979.66,0.0,0.0,0.0,Jun-2016,926.35,None,Mar-2019,699.0,695.0,0.0,NaN,1.0,Individual,NaN,NaN,None,0.0,0.0,204396.0,1.0,1.0,0.0,1.0,19.0,18005.0,73.0,2.0,3.0,6472.0,29.0,111800.0,0.0,0.0,6.0,4.0,9733.0,57830.0,27.1,0.0,0.0,113.0,192.0,2.0,2.0,4.0,2.0,NaN,0.0,6.0,0.0,5.0,5.0,13.0,17.0,6.0,20.0,27.0,5.0,22.0,0.0,0.0,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,None,None,None,NaN,NaN,None,None,None,NaN,NaN,None,NaN,NaN,NaN,Cash,N,None,None,None,NaN,NaN,NaN
2,68341763,None,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,None,home_improvement,None,605xx,IL,10.78,0.0,Aug-2000,695.0,699.0,0.0,NaN,NaN,6.0,0.0,7869.0,56.2,18.0,w,0.00,0.00,22705.924294,22705.92,20000.00,2705.92,0.0,0.0,0.0,Jun-2017,15813.30,None,Mar-2019,704.0,700.0,0.0,NaN,1.0,Joint App,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,73.0,0.0,2.0,2081.0,65.0,14000.0,2.0,5.0,1.0,6.0,31617.0,2737.0,55.9,0.0,0.0,125.0,184.0,14.0,14.0,5.0,101.0,NaN,10.0,NaN,0.0,2.0,3.0,2.0,4.0,6.0,4.0,7.0,3.0,6.0,0.0,0.0,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,None,None,None,NaN,NaN,None,None,None,NaN,NaN,None,NaN,NaN,NaN,Cash,N,None,None,None,NaN,NaN,NaN
3,66310712,None,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,Information Systems Officer,10+ years,MORTGAGE,110000.0,Source Verified,Dec-2015,Current,n,https://lendingclub.com/browse/loanDetail.acti...,None,debt_consolidation,Debt consolidation,076xx,NJ,17.06,0.0,Sep-2008,785.0,789.0,0.0,NaN,NaN,13.0,0.0,7802.0,11.6,17.0,w,15897.65,15897.65,31464.010000,31464.01,19102.35,12361.66,0.0,0.0,0.0,Feb-2019,829.90,Apr-2019,Mar-2019,679.0,675.0,0.0,NaN,1.0,Individual,NaN,NaN,None,0.0,0.0,301500.0,1.0,1.0,0.0,1.0,23.0,12609.0,70.0,1.0,1.0,6987.0,45.0,67300.0,0.0,1.0,0.0,2.0,23192.0,54962.0,12.1,0.0,0.0,36.0,87.0,2.0,2.0,1.0,2.0,NaN,NaN,NaN,0.0,4.0,5.0,8.0,10.0,2.0,10.0,13.0,5.0,13.0,0.0,0.0,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,None,None,None,NaN,NaN,None,None,None,NaN,NaN,None,NaN,NaN,NaN,Cash,N,None,None,None,NaN,NaN,NaN
4,68476807,None,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,Contract Specialist,3 years,MORTGAGE,104433.0,Source Verified,Dec-2015,Fully Paid,n,https://lendingclub.com/browse/loanDetail.acti...,None,major_purchase,Major purchase,174xx,PA,25.37,1.0,Jun-1998,695.0,699.0,3.0,12.0,NaN,12.0,0.0,21929.0,64.5,35.0,w,0.00,0.00,11740.500000,11740.50,10400.00,1340.50,0.0,0.0,0.0,Jul-2016,10128.96,None,Mar-2018,704.0,700.0,0.0,NaN,1.0,Individual,NaN,NaN,None,0.0,0.0,331730.0,1.0,3.0,0.0,3.0,14.0,73839.0,84.0,4.0,7.0,9702.0,78.0,34000.0,2.0,1.0,3.0,10.0,27644.0,4567.0,77.5,0.0,0.0,128.0,210.0,4.0,4.0,6.0,4.0,12.0,1.0,12.0,0.0,4.0,6.0,5.0,9.0,10.0,7.0,19.0,6.0,12.0,0.0,0.0,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,N,None,None,None,NaN,NaN,None,None,None,NaN,NaN,None,NaN,NaN,NaN,Cash,N,None,None,None,NaN,NaN,NaN

In [7]:
conn.execute(
    """
    select
        count(*) total_rows,
        count(distinct id) distinct_id
    from raw.lendingclub_raw
    """
).fetchdf()

   total_rows  distinct_id
0     2260701      2260701

In [8]:
conn.execute(
    """
    select
        count(*) total_rows,
        count(member_id) populated_member_id
    from raw.lendingclub_raw
    """
).fetchdf()

   total_rows  populated_member_id
0     2260701                    0

In [9]:
candidate_columns = [
    "id",
    "member_id",
    "url",
    "loan_amnt"
]

for col in candidate_columns:

    try:

        df = conn.execute(
            f"""
            select
                count(*) total_rows,
                count(distinct {col}) distinct_values
            from raw.lendingclub_raw
            """
        ).fetchdf()

        print("\n")
        print(col)

        display(df)

    except Exception as e:

        print(col, e)

id

   total_rows  distinct_values
0     2260701          2260701

member_id

   total_rows  distinct_values
0     2260701                0

url

   total_rows  distinct_values
0     2260701          2260668

loan_amnt

   total_rows  distinct_values
0     2260701             1572

In [10]:
for c in columns_df["column_name"]:
    print(c)

id
member_id
loan_amnt
funded_amnt
funded_amnt_inv
term
int_rate
installment
grade
sub_grade
emp_title
emp_length
home_ownership
annual_inc
verification_status
issue_d
loan_status
pymnt_plan
url
desc
purpose
title
zip_code
addr_state
dti
delinq_2yrs
earliest_cr_line
fico_range_low
fico_range_high
inq_last_6mths
mths_since_last_delinq
mths_since_last_record
open_acc
pub_rec
revol_bal
revol_util
total_acc
initial_list_status
out_prncp
out_prncp_inv
total_pymnt
total_pymnt_inv
total_rec_prncp
total_rec_int
total_rec_late_fee
recoveries
collection_recovery_fee
last_pymnt_d
last_pymnt_amnt
next_pymnt_d
last_credit_pull_d
last_fico_range_high
last_fico_range_low
collections_12_mths_ex_med
mths_since_last_major_derog
policy_code
application_type
annual_inc_joint
dti_joint
verification_status_joint
acc_now_delinq
tot_coll_amt
tot_cur_bal
open_acc_6m
open_act_il
open_il_12m
open_il_24m
mths_since_rcnt_il
total_bal_il
il_util
open_rv_12m
open_rv_24m
max_bal_bc
all_util
total_rev_hi_lim
inq_fi
total_cu_tl
inq_last_12m
acc_open_past_24mths
avg_cur_bal
bc_open_to_buy
bc_util
chargeoff_within_12_mths
delinq_amnt
mo_sin_old_il_acct
mo_sin_old_rev_tl_op
mo_sin_rcnt_rev_tl_op
mo_sin_rcnt_tl
mort_acc
mths_since_recent_bc
mths_since_recent_bc_dlq
mths_since_recent_inq
mths_since_recent_revol_delinq
num_accts_ever_120_pd
num_actv_bc_tl
num_actv_rev_tl
num_bc_sats
num_bc_tl
num_il_tl
num_op_rev_tl
num_rev_accts
num_rev_tl_bal_gt_0
num_sats
num_tl_120dpd_2m
num_tl_30dpd
num_tl_90g_dpd_24m
num_tl_op_past_12m
pct_tl_nvr_dlq
percent_bc_gt_75
pub_rec_bankruptcies
tax_liens
tot_hi_cred_lim
total_bal_ex_mort
total_bc_limit
total_il_high_credit_limit
revol_bal_joint
sec_app_fico_range_low
sec_app_fico_range_high
sec_app_earliest_cr_line
sec_app_inq_last_6mths
sec_app_mort_acc
sec_app_open_acc
sec_app_revol_util
sec_app_open_act_il
sec_app_num_rev_accts
sec_app_chargeoff_within_12_mths
sec_app_collections_12_mths_ex_med
sec_app_mths_since_last_major_derog
hardship_flag
hardship_type
hardship_reason
hardship_status
deferral_term
hardship_amount
hardship_start_date
hardship_end_date
payment_plan_start_date
hardship_length
hardship_dpd
hardship_loan_status
orig_projected_additional_accrued_interest
hardship_payoff_balance_amount
hardship_last_payment_amount
disbursement_method
debt_settlement_flag
debt_settlement_flag_date
settlement_status
settlement_date
settlement_amount
settlement_percentage
settlement_term

In [11]:
nulls_df = conn.execute(
    """
    select *
    from raw.lendingclub_raw
    
    """
).fetchdf()

(
    nulls_df
    .isnull()
    .sum()
    .sort_values(ascending=False)
    
)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

member_id                                     2260701
orig_projected_additional_accrued_interest    2252050
hardship_reason                               2249784
hardship_payoff_balance_amount                2249784
hardship_last_payment_amount                  2249784
payment_plan_start_date                       2249784
hardship_type                                 2249784
hardship_status                               2249784
hardship_start_date                           2249784
deferral_term                                 2249784
hardship_amount                               2249784
hardship_dpd                                  2249784
hardship_loan_status                          2249784
hardship_length                               2249784
hardship_end_date                             2249784
settlement_status                             2226455
debt_settlement_flag_date                     2226455
settlement_term                               2226455
settlement_percentage                         2226455
settlement_date                               2226455
settlement_amount                             2226455
sec_app_mths_since_last_major_derog           2224759
sec_app_revol_util                            2154517
revol_bal_joint                               2152681
sec_app_inq_last_6mths                        2152680
sec_app_num_rev_accts                         2152680
sec_app_open_acc                              2152680
sec_app_earliest_cr_line                      2152680
sec_app_fico_range_high                       2152680
sec_app_mort_acc                              2152680
sec_app_open_act_il                           2152680
sec_app_fico_range_low                        2152680
sec_app_collections_12_mths_ex_med            2152680
sec_app_chargeoff_within_12_mths              2152680
verification_status_joint                     2144971
dti_joint                                     2139995
annual_inc_joint                              2139991
desc                                          2134634
mths_since_last_record                        1901545
mths_since_recent_bc_dlq                      1741000
mths_since_last_major_derog                   1679926
mths_since_recent_revol_delinq                1520342
next_pymnt_d                                  1345343
mths_since_last_delinq                        1158535
il_util                                       1068883
mths_since_rcnt_il                             909957
all_util                                       866381
open_acc_6m                                    866163
inq_last_12m                                   866163
total_cu_tl                                    866163
open_il_24m                                    866162
max_bal_bc                                     866162
open_act_il                                    866162
open_il_12m                                    866162
open_rv_24m                                    866162
total_bal_il                                   866162
inq_fi                                         866162
open_rv_12m                                    866162
mths_since_recent_inq                          295468
emp_title                                      167002
num_tl_120dpd_2m                               153690
emp_length                                     146940
mo_sin_old_il_acct                             139104
bc_util                                         76104
percent_bc_gt_75                                75412
bc_open_to_buy                                  74968
mths_since_recent_bc                            73445
pct_tl_nvr_dlq                                  70464
avg_cur_bal                                     70379
mo_sin_rcnt_rev_tl_op                           70310
num_rev_accts                                   70310
mo_sin_old_rev_tl_op                            70310
num_op_rev_tl                                   70309
num_il_tl                                       70309
num_tl_op_past_12m                              70309
tot_coll_amt                                    70309
num_actv_rev_tl                                 70309
total_rev_hi_lim                                70309
tot_cur_bal                                     70309
num_tl_30dpd                                    70309
num_actv_bc_tl                                  70309
num_accts_ever_120_pd                           70309
num_rev_tl_bal_gt_0                             70309
mo_sin_rcnt_tl                                  70309
num_tl_90g_dpd_24m                              70309
tot_hi_cred_lim                                 70309
total_il_high_credit_limit                      70309
num_bc_tl                                       70309
num_bc_sats                                     58623
num_sats                                        58623
mort_acc                                        50063
total_bal_ex_mort                               50063
total_bc_limit                                  50063
acc_open_past_24mths                            50063
title                                           23358
last_pymnt_d                                     2460
revol_util                                       1835
dti                                              1744
pub_rec_bankruptcies                             1398
chargeoff_within_12_mths                          178
collections_12_mths_ex_med                        178
tax_liens                                         138
last_credit_pull_d                                105
inq_last_6mths                                     63
delinq_amnt                                        62
total_acc                                          62
open_acc                                           62
earliest_cr_line                                   62
pub_rec                                            62
delinq_2yrs                                        62
acc_now_delinq                                     62
annual_inc                                         37
zip_code                                           34
loan_amnt                                          33
funded_amnt                                        33
term                                               33
funded_amnt_inv                                    33
int_rate                                           33
verification_status                                33
out_prncp                                          33
purpose                                            33
pymnt_plan                                         33
loan_status                                        33
issue_d                                            33
grade                                              33
home_ownership                                     33
url                                                33
installment                                        33
sub_grade                                          33
revol_bal                                          33
policy_code                                        33
application_type                                   33
last_pymnt_amnt                                    33
last_fico_range_low                                33
addr_state                                         33
collection_recovery_fee                            33
initial_list_status                                33
last_fico_range_high                               33
fico_range_low                                     33
fico_range_high                                    33
out_prncp_inv                                      33
total_pymnt_inv                                    33
total_pymnt                                        33
total_rec_prncp                                    33
recoveries                                         33
total_rec_late_fee                                 33
total_rec_int                                      33
disbursement_method                                33
hardship_flag                                      33
debt_settlement_flag                               33
id                                                  0
dtype: int64

In [12]:
conn.execute(
    """
    select
        loan_status,
        count(*) loans
    from raw.lendingclub_raw
    group by 1
    order by 2 desc
    """
).fetchdf()

                                         loan_status    loans
0                                         Fully Paid  1076751
1                                            Current   878317
2                                        Charged Off   268559
3                                 Late (31-120 days)    21467
4                                    In Grace Period     8436
5                                  Late (16-30 days)     4349
6  Does not meet the credit policy. Status:Fully ...     1988
7  Does not meet the credit policy. Status:Charge...      761
8                                            Default       40
9                                               None       33

In [13]:
conn.execute(
    """
    select *
    from raw.lendingclub_raw
    where id is null
    """
).fetchdf()

Empty DataFrame
Columns: [id, member_id, loan_amnt, funded_amnt, funded_amnt_inv, term, int_rate, installment, grade, sub_grade, emp_title, emp_length, home_ownership, annual_inc, verification_status, issue_d, loan_status, pymnt_plan, url, desc, purpose, title, zip_code, addr_state, dti, delinq_2yrs, earliest_cr_line, fico_range_low, fico_range_high, inq_last_6mths, mths_since_last_delinq, mths_since_last_record, open_acc, pub_rec, revol_bal, revol_util, total_acc, initial_list_status, out_prncp, out_prncp_inv, total_pymnt, total_pymnt_inv, total_rec_prncp, total_rec_int, total_rec_late_fee, recoveries, collection_recovery_fee, last_pymnt_d, last_pymnt_amnt, next_pymnt_d, last_credit_pull_d, last_fico_range_high, last_fico_range_low, collections_12_mths_ex_med, mths_since_last_major_derog, policy_code, application_type, annual_inc_joint, dti_joint, verification_status_joint, acc_now_delinq, tot_coll_amt, tot_cur_bal, open_acc_6m, open_act_il, open_il_12m, open_il_24m, mths_since_rcnt_il, total_bal_il, il_util, open_rv_12m, open_rv_24m, max_bal_bc, all_util, total_rev_hi_lim, inq_fi, total_cu_tl, inq_last_12m, acc_open_past_24mths, avg_cur_bal, bc_open_to_buy, bc_util, chargeoff_within_12_mths, delinq_amnt, mo_sin_old_il_acct, mo_sin_old_rev_tl_op, mo_sin_rcnt_rev_tl_op, mo_sin_rcnt_tl, mort_acc, mths_since_recent_bc, mths_since_recent_bc_dlq, mths_since_recent_inq, mths_since_recent_revol_delinq, num_accts_ever_120_pd, num_actv_bc_tl, num_actv_rev_tl, num_bc_sats, num_bc_tl, num_il_tl, num_op_rev_tl, ...]
Index: []

In [14]:
conn.execute(
    """
    select
        min(issue_d),
        max(issue_d)
    from raw.lendingclub_raw
    """
).fetchdf()

  min(issue_d) max(issue_d)
0     Apr-2008     Sep-2018

In [15]:
conn.execute(
    """
    select
        application_type,
        count(*) loans
    from raw.lendingclub_raw
    group by 1
    order by 2 desc
    """
).fetchdf()

  application_type    loans
0       Individual  2139958
1        Joint App   120710
2             None       33

In [16]:
conn.execute(
    """
    select
        id,
        loan_status,
        issue_d
    from raw.lendingclub_raw
    where try_cast(id as bigint) is null
    """
).fetchdf()

                                                  id loan_status issue_d
0   Total amount funded in policy code 1: 6417608175        None    None
1   Total amount funded in policy code 2: 1944088810        None    None
2   Total amount funded in policy code 1: 1741781700        None    None
3    Total amount funded in policy code 2: 564202131        None    None
4   Total amount funded in policy code 1: 1791201400        None    None
5    Total amount funded in policy code 2: 651669342        None    None
6   Total amount funded in policy code 1: 1443412975        None    None
7    Total amount funded in policy code 2: 511988838        None    None
8   Total amount funded in policy code 1: 2063142975        None    None
9    Total amount funded in policy code 2: 823319310        None    None
10  Total amount funded in policy code 1: 1538432075        None    None
11   Total amount funded in policy code 2: 608903141        None    None
12  Total amount funded in policy code 1: 2087217200        None    None
13   Total amount funded in policy code 2: 662815446        None    None
14  Total amount funded in policy code 1: 3503840175        None    None
15   Total amount funded in policy code 2: 873652739        None    None
16  Total amount funded in policy code 1: 2050909275        None    None
17   Total amount funded in policy code 2: 820109297        None    None
18  Total amount funded in policy code 1: 2080429200        None    None
19   Total amount funded in policy code 2: 737901574        None    None
20          Loans that do not meet the credit policy        None    None
21   Total amount funded in policy code 1: 460296150        None    None
22           Total amount funded in policy code 2: 0        None    None
23  Total amount funded in policy code 1: 1437969475        None    None
24   Total amount funded in policy code 2: 520780182        None    None
25  Total amount funded in policy code 1: 2700702175        None    None
26    Total amount funded in policy code 2: 81866225        None    None
27  Total amount funded in policy code 1: 1404586950        None    None
28   Total amount funded in policy code 2: 567447023        None    None
29  Total amount funded in policy code 1: 1817354125        None    None
30   Total amount funded in policy code 2: 620899600        None    None
31  Total amount funded in policy code 1: 1465324575        None    None
32   Total amount funded in policy code 2: 521953170        None    None

In [17]:
conn.execute(
    """
    select
        count(*)
    from raw.lendingclub_raw
    where try_cast(id as bigint) is null
    """
).fetchdf()

   count_star()
0            33

In [18]:
conn.execute(
    """
    select
        typeof(id)
    from raw.lendingclub_raw
    limit 1
    """
).fetchdf()

  typeof(id)
0    VARCHAR

In [19]:
conn.execute(
    """
    select
        count(*) as loans,
        count(distinct id) as distinct_id
    from raw.lendingclub_raw
    where try_cast(id as bigint) is not null
    """
).fetchdf()

     loans  distinct_id
0  2260668      2260668

In [20]:
conn.execute(
    """
    select
        min(issue_d) as min_issue_d,
        max(issue_d) as max_issue_d
    from raw.lendingclub_raw
    where try_cast(id as bigint) is not null
    """
).fetchdf()

  min_issue_d max_issue_d
0    Apr-2008    Sep-2018

In [21]:
conn.execute(
    """
    select
        application_type,
        count(*) loans
    from raw.lendingclub_raw
    where try_cast(id as bigint) is not null
    group by 1
    order by 2 desc
    """
).fetchdf()

  application_type    loans
0       Individual  2139958
1        Joint App   120710

In [22]:
loan_status_df = conn.execute(
    """
    select
        loan_status,
        count(*) loans
    from raw.lendingclub_raw
    where try_cast(id as bigint) is not null
    group by 1
    order by 2 desc
    """
).fetchdf()

loan_status_df["pct"] = (
    loan_status_df["loans"]
    / loan_status_df["loans"].sum()
    * 100
).round(2)

loan_status_df

                                         loan_status    loans    pct
0                                         Fully Paid  1076751  47.63
1                                            Current   878317  38.85
2                                        Charged Off   268559  11.88
3                                 Late (31-120 days)    21467   0.95
4                                    In Grace Period     8436   0.37
5                                  Late (16-30 days)     4349   0.19
6  Does not meet the credit policy. Status:Fully ...     1988   0.09
7  Does not meet the credit policy. Status:Charge...      761   0.03
8                                            Default       40   0.00

In [23]:
conn.execute(
    """
    select
        policy_code,
        count(*) loans
    from raw.lendingclub_raw
    where try_cast(id as bigint) is not null
    group by 1
    order by 1
    """
).fetchdf()

   policy_code    loans
0          1.0  2260668

In [24]:
conn.execute(
    """
    select
        grade,
        count(*) loans
    from raw.lendingclub_raw
    where try_cast(id as bigint) is not null
    group by 1
    order by 1
    """
).fetchdf()

  grade   loans
0     A  433027
1     B  663557
2     C  650053
3     D  324424
4     E  135639
5     F   41800
6     G   12168

In [25]:
conn.execute(
    """
    select
        count(*) duplicate_loans
    from
    (
        select
            id,
            count(*) cnt
        from raw.lendingclub_raw
        where try_cast(id as bigint) is not null
        group by id
        having count(*) > 1
    )
    """
).fetchdf()

   duplicate_loans
0                0

In [26]:
profile_df = conn.execute(
    """
    select *
    from raw.lendingclub_raw
    where try_cast(id as bigint) is not null
    """
).fetchdf()

summary = []

for col in profile_df.columns:

    summary.append(
        {
            "column_name": col,
            "dtype": str(profile_df[col].dtype),
            "rows": len(profile_df),
            "nulls": profile_df[col].isna().sum(),
            "null_pct": round(
                profile_df[col].isna().mean() * 100,
                2
            ),
            "distinct_values":
                profile_df[col].nunique(dropna=True)
        }
    )

profile_summary = (
    pd.DataFrame(summary)
    .sort_values(
        ["null_pct", "column_name"],
        ascending=[False, True]
    )
)

profile_summary

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,column_name,dtype,rows,nulls,null_pct,distinct_values
1,member_id,object,2260668,2260668,100.00,0
140,orig_projected_additional_accrued_interest,float64,2260668,2252017,99.62,7487
132,deferral_term,float64,2260668,2249751,99.52,1
133,hardship_amount,float64,2260668,2249751,99.52,9162
138,hardship_dpd,float64,2260668,2249751,99.52,34
135,hardship_end_date,object,2260668,2249751,99.52,28
142,hardship_last_payment_amount,float64,2260668,2249751,99.52,9045
137,hardship_length,float64,2260668,2249751,99.52,1
139,hardship_loan_status,object,2260668,2249751,99.52,5
141,hardship_payoff_balance_amount,float64,2260668,2249751,99.52,10893
130,hardship_reason,object,2260668,2249751,99.52,9
134,hardship_start_date,object,2260668,2249751,99.52,27
131,hardship_status,object,2260668,2249751,99.52,3
129,hardship_type,object,2260668,2249751,99.52,1
136,payment_plan_start_date,object,2260668,2249751,99.52,27
145,debt_settlement_flag_date,object,2260668,2226422,98.49,83
148,settlement_amount,float64,2260668,2226422,98.49,21941
147,settlement_date,object,2260668,2226422,98.49,90
149,settlement_percentage,float64,2260668,2226422,98.49,2070
146,settlement_status,object,2260668,2226422,98.49,3
150,settlement_term,float64,2260668,2226422,98.49,40
127,sec_app_mths_since_last_major_derog,float64,2260668,2224726,98.41,140
122,sec_app_revol_util,float64,2260668,2154484,95.30,1216
115,revol_bal_joint,float64,2260668,2152648,95.22,56875
125,sec_app_chargeoff_within_12_mths,float64,2260668,2152647,95.22,22
126,sec_app_collections_12_mths_ex_med,float64,2260668,2152647,95.22,18
118,sec_app_earliest_cr_line,object,2260668,2152647,95.22,663
117,sec_app_fico_range_high,float64,2260668,2152647,95.22,62
116,sec_app_fico_range_low,float64,2260668,2152647,95.22,62
119,sec_app_inq_last_6mths,float64,2260668,2152647,95.22,7
120,sec_app_mort_acc,float64,2260668,2152647,95.22,23
124,sec_app_num_rev_accts,float64,2260668,2152647,95.22,86
121,sec_app_open_acc,float64,2260668,2152647,95.22,67
123,sec_app_open_act_il,float64,2260668,2152647,95.22,40
59,verification_status_joint,object,2260668,2144938,94.88,3
57,annual_inc_joint,float64,2260668,2139958,94.66,17633
58,dti_joint,float64,2260668,2139962,94.66,4018
19,desc,object,2260668,2134601,94.42,124501
31,mths_since_last_record,float64,2260668,1901512,84.11,129
90,mths_since_recent_bc_dlq,float64,2260668,1740967,77.01,177
54,mths_since_last_major_derog,float64,2260668,1679893,74.31,183
92,mths_since_recent_revol_delinq,float64,2260668,1520309,67.25,179
49,next_pymnt_d,object,2260668,1345310,59.51,106
30,mths_since_last_delinq,float64,2260668,1158502,51.25,173
69,il_util,float64,2260668,1068850,47.28,280
67,mths_since_rcnt_il,float64,2260668,909924,40.25,405
73,all_util,float64,2260668,866348,38.32,188
75,inq_fi,float64,2260668,866129,38.31,33
77,inq_last_12m,float64,2260668,866130,38.31,48
72,max_bal_bc,float64,2260668,866129,38.31,33726
63,open_acc_6m,float64,2260668,866130,38.31,19
64,open_act_il,float64,2260668,866129,38.31,54
65,open_il_12m,float64,2260668,866129,38.31,19
66,open_il_24m,float64,2260668,866129,38.31,31
70,open_rv_12m,float64,2260668,866129,38.31,29
71,open_rv_24m,float64,2260668,866129,38.31,50
68,total_bal_il,float64,2260668,866129,38.31,162249
76,total_cu_tl,float64,2260668,866130,38.31,62
91,mths_since_recent_inq,float64,2260668,295435,13.07,26
10,emp_title,object,2260668,166969,7.39,512694
103,num_tl_120dpd_2m,float64,2260668,153657,6.80,7
11,emp_length,object,2260668,146907,6.50,11
84,mo_sin_old_il_acct,float64,2260668,139071,6.15,566
81,bc_util,float64,2260668,76071,3.36,1494
108,percent_bc_gt_75,float64,2260668,75379,3.33,284
80,bc_open_to_buy,float64,2260668,74935,3.31,91500
89,mths_since_recent_bc,float64,2260668,73412,3.25,546
107,pct_tl_nvr_dlq,float64,2260668,70431,3.12,690
79,avg_cur_bal,float64,2260668,70346,3.11,88597
85,mo_sin_old_rev_tl_op,float64,2260668,70277,3.11,787
86,mo_sin_rcnt_rev_tl_op,float64,2260668,70277,3.11,333
87,mo_sin_rcnt_tl,float64,2260668,70276,3.11,232
93,num_accts_ever_120_pd,float64,2260668,70276,3.11,44
94,num_actv_bc_tl,float64,2260668,70276,3.11,42
95,num_actv_rev_tl,float64,2260668,70276,3.11,57
97,num_bc_tl,float64,2260668,70276,3.11,76
98,num_il_tl,float64,2260668,70276,3.11,122
99,num_op_rev_tl,float64,2260668,70276,3.11,81
100,num_rev_accts,float64,2260668,70277,3.11,117
101,num_rev_tl_bal_gt_0,float64,2260668,70276,3.11,50
104,num_tl_30dpd,float64,2260668,70276,3.11,5
105,num_tl_90g_dpd_24m,float64,2260668,70276,3.11,34
106,num_tl_op_past_12m,float64,2260668,70276,3.11,33
61,tot_coll_amt,float64,2260668,70276,3.11,15574
62,tot_cur_bal,float64,2260668,70276,3.11,487688
111,tot_hi_cred_lim,float64,2260668,70276,3.11,529972
114,total_il_high_credit_limit,float64,2260668,70276,3.11,194137
74,total_rev_hi_lim,float64,2260668,70276,3.11,34220
96,num_bc_sats,float64,2260668,58590,2.59,60
102,num_sats,float64,2260668,58590,2.59,91
78,acc_open_past_24mths,float64,2260668,50030,2.21,57
88,mort_acc,float64,2260668,50030,2.21,47
112,total_bal_ex_mort,float64,2260668,50030,2.21,212777
113,total_bc_limit,float64,2260668,50030,2.21,20309
21,title,object,2260668,23325,1.03,63155
47,last_pymnt_d,object,2260668,2427,0.11,136
24,dti,float64,2260668,1711,0.08,10845
35,revol_util,float64,2260668,1802,0.08,1430
109,pub_rec_bankruptcies,float64,2260668,1365,0.06,12
82,chargeoff_within_12_mths,float64,2260668,145,0.01,11
53,collections_12_mths_ex_med,float64,2260668,145,0.01,16
60,acc_now_delinq,float64,2260668,29,0.00,9
23,addr_state,object,2260668,0,0.00,51
13,annual_inc,float64,2260668,4,0.00,89368
56,application_type,object,2260668,0,0.00,2
46,collection_recovery_fee,float64,2260668,0,0.00,146222
144,debt_settlement_flag,object,2260668,0,0.00,2
25,delinq_2yrs,float64,2260668,29,0.00,37
83,delinq_amnt,float64,2260668,29,0.00,2617
143,disbursement_method,object,2260668,0,0.00,2
26,earliest_cr_line,object,2260668,29,0.00,754
28,fico_range_high,float64,2260668,0,0.00,48
27,fico_range_low,float64,2260668,0,0.00,48
3,funded_amnt,float64,2260668,0,0.00,1572
4,funded_amnt_inv,float64,2260668,0,0.00,10057
8,grade,object,2260668,0,0.00,7
128,hardship_flag,object,2260668,0,0.00,2
12,home_ownership,object,2260668,0,0.00,6
0,id,object,2260668,0,0.00,2260668
37,initial_list_status,object,2260668,0,0.00,2
29,inq_last_6mths,float64,2260668,30,0.00,28
7,installment,float64,2260668,0,0.00,93301
6,int_rate,float64,2260668,0,0.00,673
15,issue_d,object,2260668,0,0.00,139
50,last_credit_pull_d,object,2260668,72,0.00,141
51,last_fico_range_high,float64,2260668,0,0.00,72
52,last_fico_range_low,float64,2260668,0,0.00,71
48,last_pymnt_amnt,float64,2260668,0,0.00,704467
2,loan_amnt,float64,2260668,0,0.00,1572
16,loan_status,object,2260668,0,0.00,9
32,open_acc,float64,2260668,29,0.00,91
38,out_prncp,float64,2260668,0,0.00,356141
39,out_prncp_inv,float64,2260668,0,0.00,368481
55,policy_code,float64,2260668,0,0.00,1
33,pub_rec,float64,2260668,29,0.00,43
20,purpose,object,2260668,0,0.00,14
17,pymnt_plan,object,2260668,0,0.00,2
45,recoveries,float64,2260668,0,0.00,132777
34,revol_bal,float64,2260668,0,0.00,102251
9,sub_grade,object,2260668,0,0.00,35
110,tax_liens,float64,2260668,105,0.00,42
5,term,object,2260668,0,0.00,2
36,total_acc,float64,2260668,29,0.00,152
40,total_pymnt,float64,2260668,0,0.00,1633878
41,total_pymnt_inv,float64,2260668,0,0.00,1311099
43,total_rec_int,float64,2260668,0,0.00,635921
44,total_rec_late_fee,float64,2260668,0,0.00,18375
42,total_rec_prncp,float64,2260668,0,0.00,486463
18,url,object,2260668,0,0.00,2260668
14,verification_status,object,2260668,0,0.00,3
22,zip_code,object,2260668,1,0.00,956

# Clean Layer Specification v1

## Objective

Transform raw LendingClub data into a trusted clean dataset.

## Source

raw.lendingclub_raw

## Target

clean.lendingclub_clean

## Cleaning Rules

### Rule 1

Remove footer rows.

Condition:

```sql
try_cast(id as bigint) is not null
```

### Rule 2

Drop member_id.

Reason:

100% null.

### Rule 3

Drop policy_code.

Reason:

Single value.

### Rule 4

Standardize date columns.

Convert:

- issue_d
- earliest_cr_line
- last_pymnt_d
- next_pymnt_d
- last_credit_pull_d
- hardship_start_date
- hardship_end_date
- payment_plan_start_date
- settlement_date
- debt_settlement_flag_date

to proper date types.

### Rule 5

Preserve sparse columns.

Do not remove:

- hardship_*
- settlement_*
- joint applicant columns

Reason:

Business meaning is important despite sparsity.

### Rule 6

Preserve original values.

No imputation in clean layer.

Imputation belongs to feature engineering.

### Rule 7

Maintain loan-level grain.

1 row = 1 loan.

In [13]:
import duckdb

conn = duckdb.connect(
    r"D:\project_lighthouse\projects\P0_Data_Platform\datasets\lendingclub\data\warehouse\duckdb\lendingclub.duckdb"
)

In [6]:
conn.execute("""
select count(*)
from core.loan_master
""").fetchdf()

   count_star()
0       2260668

In [7]:
conn.execute("""
describe core.loan_master
""").fetchdf().head(10)

       column_name column_type null   key default extra
0          loan_id      BIGINT  YES  None    None  None
1        loan_amnt      DOUBLE  YES  None    None  None
2      funded_amnt      DOUBLE  YES  None    None  None
3  funded_amnt_inv      DOUBLE  YES  None    None  None
4             term     VARCHAR  YES  None    None  None
5         int_rate      DOUBLE  YES  None    None  None
6      installment      DOUBLE  YES  None    None  None
7            grade     VARCHAR  YES  None    None  None
8        sub_grade     VARCHAR  YES  None    None  None
9        emp_title     VARCHAR  YES  None    None  None

In [9]:
conn.execute("""
select
    issue_d,
    count(*) as loans
from core.loan_master
group by 1
order by 1

""").fetchdf()

      issue_d  loans
0    Apr-2008    259
1    Apr-2009    333
2    Apr-2010    912
3    Apr-2011   1563
4    Apr-2012   3230
5    Apr-2013   9419
6    Apr-2014  19071
7    Apr-2015  35427
8    Apr-2016  36432
9    Apr-2017  29683
10   Apr-2018  42928
11   Aug-2007     74
12   Aug-2008    100
13   Aug-2009    446
14   Aug-2010   1175
15   Aug-2011   1934
16   Aug-2012   5419
17   Aug-2013  12674
18   Aug-2014  18814
19   Aug-2015  35886
20   Aug-2016  36280
21   Aug-2017  43573
22   Aug-2018  46079
23   Dec-2007    172
24   Dec-2008    253
25   Dec-2009    658
26   Dec-2010   1335
27   Dec-2011   2267
28   Dec-2012   6066
29   Dec-2013  15020
30   Dec-2014  10307
31   Dec-2015  44343
32   Dec-2016  36183
33   Dec-2017  38154
34   Dec-2018  40134
35   Feb-2008    306
36   Feb-2009    302
37   Feb-2010    682
38   Feb-2011   1298
39   Feb-2012   2560
40   Feb-2013   7561
41   Feb-2014  15269
42   Feb-2015  23770
43   Feb-2016  39529
44   Feb-2017  27763
45   Feb-2018  32746
46   Jan-2008    305
47   Jan-2009    269
48   Jan-2010    662
49   Jan-2011   1380
50   Jan-2012   2602
51   Jan-2013   6872
52   Jan-2014  15628
53   Jan-2015  35107
54   Jan-2016  32366
55   Jan-2017  31835
56   Jan-2018  36347
57   Jul-2007     63
58   Jul-2008    141
59   Jul-2009    411
60   Jul-2010   1204
61   Jul-2011   1875
62   Jul-2012   4627
63   Jul-2013  11910
64   Jul-2014  29306
65   Jul-2015  45962
66   Jul-2016  34696
67   Jul-2017  39415
68   Jul-2018  43089
69   Jun-2007     24
70   Jun-2008    124
71   Jun-2009    406
72   Jun-2010   1105
73   Jun-2011   1835
74   Jun-2012   3817
75   Jun-2013  10899
76   Jun-2014  17179
77   Jun-2015  28485
78   Jun-2016  33019
79   Jun-2017  38087
80   Jun-2018  41533
81   Mar-2008    402
82   Mar-2009    324
83   Mar-2010    828
84   Mar-2011   1448
85   Mar-2012   2914
86   Mar-2013   8273
87   Mar-2014  16513
88   Mar-2015  25400
89   Mar-2016  61992
90   Mar-2017  37181
91   Mar-2018  38771
92   May-2008    115
93   May-2009    359
94   May-2010    989
95   May-2011   1704
96   May-2012   3400
97   May-2013  10350
98   May-2014  19099
99   May-2015  31913
100  May-2016  28403
101  May-2017  37681
102  May-2018  46311
103  Nov-2007    112
104  Nov-2008    209
105  Nov-2009    662
106  Nov-2010   1224
107  Nov-2011   2232
108  Nov-2012   6382
109  Nov-2013  14720
110  Nov-2014  25054
111  Nov-2015  37530
112  Nov-2016  34591
113  Nov-2017  42343
114  Nov-2018  41973
115  Oct-2007    105
116  Oct-2008    122
117  Oct-2009    604
118  Oct-2010   1232
119  Oct-2011   2118
120  Oct-2012   6263
121  Oct-2013  14129
122  Oct-2014  38783
123  Oct-2015  48631
124  Oct-2016  32772
125  Oct-2017  38151
126  Oct-2018  46305
127  Sep-2007     53
128  Sep-2008     57
129  Sep-2009    507
130  Sep-2010   1189
131  Sep-2011   2067
132  Sep-2012   6087
133  Sep-2013  12987
134  Sep-2014  10606
135  Sep-2015  28641
136  Sep-2016  28144
137  Sep-2017  39713
138  Sep-2018  39026

In [10]:
date_cols = [
    "issue_d",
    "earliest_cr_line",
    "last_pymnt_d",
    "next_pymnt_d",
    "last_credit_pull_d"
]

for c in date_cols:
    print("\n", c)
    print(
        conn.execute(
            f"""
            select distinct {c}
            from core.loan_master
            where {c} is not null
            limit 10
            """
        ).fetchdf()
    )

 issue_d
    issue_d
0  Jul-2015
1  Jun-2017
2  Apr-2017
3  Feb-2010
4  Feb-2009
5  Dec-2008
6  Apr-2008
7  Oct-2010
8  Sep-2010
9  Apr-2013

 earliest_cr_line
  earliest_cr_line
0         Oct-1987
1         Sep-2001
2         Apr-2001
3         Nov-2001
4         Jan-2001
5         Dec-1987
6         Jun-2004
7         Dec-2002
8         Jan-2002
9         Jul-1995

 last_pymnt_d
  last_pymnt_d
0     Jun-2016
1     Aug-2018
2     Nov-2018
3     Aug-2016
4     Nov-2017
5     Jul-2018
6     Feb-2016
7     Apr-2014
8     Oct-2014
9     Apr-2011

 next_pymnt_d
  next_pymnt_d
0     Nov-2013
1     Sep-2012
2     May-2012
3     Dec-2015
4     May-2011
5     Dec-2009
6     Jun-2008
7     Feb-2008
8     Sep-2013
9     May-2014

 last_credit_pull_d
  last_credit_pull_d
0           Oct-2017
1           Mar-2017
2           Oct-2016
3           May-2017
4           May-2016
5           Dec-2015
6           Nov-2013
7           Sep-2012
8           May-2012
9           May-2011

In [11]:
date_cols = [
    "issue_d",
    "earliest_cr_line",
    "last_pymnt_d",
    "next_pymnt_d",
    "last_credit_pull_d"
]

for col in date_cols:

    result = conn.execute(
        f"""
        select
            count(*) total_rows,
            count({col}) populated_rows
        from core.loan_master
        """
    ).fetchdf()

    print("\n", col)
    print(result)

 issue_d
   total_rows  populated_rows
0     2260668         2260668

 earliest_cr_line
   total_rows  populated_rows
0     2260668         2260639

 last_pymnt_d
   total_rows  populated_rows
0     2260668         2258241

 next_pymnt_d
   total_rows  populated_rows
0     2260668          915358

 last_credit_pull_d
   total_rows  populated_rows
0     2260668         2260596

In [ ]:
conn.close()

print("Connection closed")

Connection closed

:

In [14]:
conn.execute("""
describe core.loan_master_v2
""").fetchdf().head(15)

              column_name column_type null   key default extra
0                 loan_id      BIGINT  YES  None    None  None
1              issue_date   TIMESTAMP  YES  None    None  None
2    earliest_credit_date   TIMESTAMP  YES  None    None  None
3       last_payment_date   TIMESTAMP  YES  None    None  None
4       next_payment_date   TIMESTAMP  YES  None    None  None
5   last_credit_pull_date   TIMESTAMP  YES  None    None  None
6               loan_amnt      DOUBLE  YES  None    None  None
7             funded_amnt      DOUBLE  YES  None    None  None
8         funded_amnt_inv      DOUBLE  YES  None    None  None
9                    term     VARCHAR  YES  None    None  None
10               int_rate      DOUBLE  YES  None    None  None
11            installment      DOUBLE  YES  None    None  None
12                  grade     VARCHAR  YES  None    None  None
13              sub_grade     VARCHAR  YES  None    None  None
14              emp_title     VARCHAR  YES  None    None  None